--------------------------------------------------------
--  File creato - lunedì-luglio-08-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "SYS"."CLIENTE" 
   (	"ID_CLIENTE" NUMBER, 
	"PRIVATO" NUMBER(*,0), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRENOTAZIONE_PRIVATO
--------------------------------------------------------

  CREATE TABLE "SYS"."PRENOTAZIONE_PRIVATO" 
   (	"ID_PRENOTAZIONE" VARCHAR2(50 BYTE), 
	"ID_CLIENTE" NUMBER, 
	"ID_VEICOLO_PRIVATO" NUMBER, 
	"NOME" VARCHAR2(20 BYTE), 
	"COGNOME" VARCHAR2(20 BYTE), 
	"NUM_PARTECIPANTI" NUMBER, 
	"PREZZO_TOTALE" FLOAT(126), 
	"DATA_INIZIO" DATE, 
	"DATA_FINE" DATE, 
	"STATO" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRENOTAZIONE_PUBBLICO
--------------------------------------------------------

  CREATE TABLE "SYS"."PRENOTAZIONE_PUBBLICO" 
   (	"ID_PRENOTAZIONE" VARCHAR2(50 BYTE), 
	"ID_CLIENTE" NUMBER, 
	"ID_VEICOLO_PUBBLICO" NUMBER, 
	"NOME" VARCHAR2(20 BYTE), 
	"COGNOME" VARCHAR2(20 BYTE), 
	"NUM_PARTECIPANTI" NUMBER, 
	"PREZZO_TOTALE" FLOAT(126), 
	"DATA_PARTENZA" DATE, 
	"LUOGO_PARTEZA" VARCHAR2(20 BYTE), 
	"LUOGO_ARRIVO" VARCHAR2(20 BYTE), 
	"STATO" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VEICOLO_PRIVATO
--------------------------------------------------------

  CREATE TABLE "SYS"."VEICOLO_PRIVATO" 
   (	"ID_VEICOLO_PRIVATO" NUMBER, 
	"NUM_POSTI_DISPONIBILI" NUMBER, 
	"PREZZO" FLOAT(126), 
	"TIPO" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VEICOLO_PUBBLICO
--------------------------------------------------------

  CREATE TABLE "SYS"."VEICOLO_PUBBLICO" 
   (	"ID_VEICOLO_PUBBLICO" NUMBER, 
	"NUM_POSTI_DISPONIBILI" NUMBER, 
	"PREZZO" FLOAT(126), 
	"TIPO" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYS.CLIENTE
SET DEFINE OFF;
REM INSERTING into SYS.PRENOTAZIONE_PRIVATO
SET DEFINE OFF;
REM INSERTING into SYS.PRENOTAZIONE_PUBBLICO
SET DEFINE OFF;
REM INSERTING into SYS.VEICOLO_PRIVATO
SET DEFINE OFF;
REM INSERTING into SYS.VEICOLO_PUBBLICO
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "SYS"."CLIENTE" ADD CONSTRAINT "CLIENTE_UK1" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."CLIENTE" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."CLIENTE" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CLIENTE" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CLIENTE" MODIFY ("PRIVATO" NOT NULL ENABLE);
  ALTER TABLE "SYS"."CLIENTE" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRENOTAZIONE_PRIVATO
--------------------------------------------------------

  ALTER TABLE "SYS"."PRENOTAZIONE_PRIVATO" ADD CONSTRAINT "PRENOTAZIONE_PRIVATO_PK" PRIMARY KEY ("ID_PRENOTAZIONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."PRENOTAZIONE_PRIVATO" MODIFY ("STATO" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PRENOTAZIONE_PRIVATO" MODIFY ("DATA_FINE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PRENOTAZIONE_PRIVATO" MODIFY ("DATA_INIZIO" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PRENOTAZIONE_PRIVATO" MODIFY ("PREZZO_TOTALE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PRENOTAZIONE_PRIVATO" MODIFY ("NUM_PARTECIPANTI" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PRENOTAZIONE_PRIVATO" MODIFY ("COGNOME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PRENOTAZIONE_PRIVATO" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PRENOTAZIONE_PRIVATO" MODIFY ("ID_VEICOLO_PRIVATO" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PRENOTAZIONE_PRIVATO" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PRENOTAZIONE_PRIVATO" MODIFY ("ID_PRENOTAZIONE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRENOTAZIONE_PUBBLICO
--------------------------------------------------------

  ALTER TABLE "SYS"."PRENOTAZIONE_PUBBLICO" ADD CONSTRAINT "PRENOTAZIONE_PUBBLICO_PK" PRIMARY KEY ("ID_PRENOTAZIONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."PRENOTAZIONE_PUBBLICO" MODIFY ("STATO" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PRENOTAZIONE_PUBBLICO" MODIFY ("LUOGO_ARRIVO" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PRENOTAZIONE_PUBBLICO" MODIFY ("LUOGO_PARTEZA" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PRENOTAZIONE_PUBBLICO" MODIFY ("DATA_PARTENZA" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PRENOTAZIONE_PUBBLICO" MODIFY ("PREZZO_TOTALE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PRENOTAZIONE_PUBBLICO" MODIFY ("NUM_PARTECIPANTI" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PRENOTAZIONE_PUBBLICO" MODIFY ("COGNOME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PRENOTAZIONE_PUBBLICO" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PRENOTAZIONE_PUBBLICO" MODIFY ("ID_VEICOLO_PUBBLICO" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PRENOTAZIONE_PUBBLICO" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PRENOTAZIONE_PUBBLICO" MODIFY ("ID_PRENOTAZIONE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VEICOLO_PRIVATO
--------------------------------------------------------

  ALTER TABLE "SYS"."VEICOLO_PRIVATO" ADD CONSTRAINT "VEICOLO_PRIVATO_PK" PRIMARY KEY ("ID_VEICOLO_PRIVATO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."VEICOLO_PRIVATO" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "SYS"."VEICOLO_PRIVATO" MODIFY ("PREZZO" NOT NULL ENABLE);
  ALTER TABLE "SYS"."VEICOLO_PRIVATO" MODIFY ("NUM_POSTI_DISPONIBILI" NOT NULL ENABLE);
  ALTER TABLE "SYS"."VEICOLO_PRIVATO" MODIFY ("ID_VEICOLO_PRIVATO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VEICOLO_PUBBLICO
--------------------------------------------------------

  ALTER TABLE "SYS"."VEICOLO_PUBBLICO" ADD CONSTRAINT "VEICOLO_PUBBLICO_PK" PRIMARY KEY ("ID_VEICOLO_PUBBLICO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."VEICOLO_PUBBLICO" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "SYS"."VEICOLO_PUBBLICO" MODIFY ("PREZZO" NOT NULL ENABLE);
  ALTER TABLE "SYS"."VEICOLO_PUBBLICO" MODIFY ("NUM_POSTI_DISPONIBILI" NOT NULL ENABLE);
  ALTER TABLE "SYS"."VEICOLO_PUBBLICO" MODIFY ("ID_VEICOLO_PUBBLICO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PRENOTAZIONE_PRIVATO
--------------------------------------------------------

  ALTER TABLE "SYS"."PRENOTAZIONE_PRIVATO" ADD CONSTRAINT "PRENOTAZIONE_PRIVATO_FK1" FOREIGN KEY ("ID_VEICOLO_PRIVATO")
	  REFERENCES "SYS"."VEICOLO_PRIVATO" ("ID_VEICOLO_PRIVATO") ENABLE;
  ALTER TABLE "SYS"."PRENOTAZIONE_PRIVATO" ADD CONSTRAINT "PRENOTAZIONE_PRIVATO_FK2" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "SYS"."CLIENTE" ("ID_CLIENTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRENOTAZIONE_PUBBLICO
--------------------------------------------------------

  ALTER TABLE "SYS"."PRENOTAZIONE_PUBBLICO" ADD CONSTRAINT "PRENOTAZIONE_PUBBLICO_FK1" FOREIGN KEY ("ID_VEICOLO_PUBBLICO")
	  REFERENCES "SYS"."VEICOLO_PUBBLICO" ("ID_VEICOLO_PUBBLICO") ENABLE;
  ALTER TABLE "SYS"."PRENOTAZIONE_PUBBLICO" ADD CONSTRAINT "PRENOTAZIONE_PUBBLICO_FK2" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "SYS"."CLIENTE" ("ID_CLIENTE") ENABLE;
